#!/usr/bin/env python3
"""互動式取得 cookies（不需要瀏覽器擴充功能）。

開啟一個乾淨的 Chromium 視窗讓你登入目標平台，登入完成後回到終端機按
Enter，cookies 會匯出成 yt-dlp 可用的 Netscape 格式檔案。

用法（或透過 ./scripts/get-cookies.sh）：
    backend/.venv/bin/python scripts/get-cookies.py facebook
    backend/.venv/bin/python scripts/get-cookies.py tiktok -o cookies.txt
    backend/.venv/bin/python scripts/get-cookies.py https://example.com/login
"""

import argparse
import sys
from pathlib import Path

SITES = {
    "facebook": "https://www.facebook.com/login",
    "x": "https://x.com/i/flow/login",
    "twitter": "https://x.com/i/flow/login",
    "tiktok": "https://www.tiktok.com/login",
    "youtube": "https://accounts.google.com/ServiceLogin?continue=https://www.youtube.com",
    "instagram": "https://www.instagram.com/accounts/login/",
    "bilibili": "https://passport.bilibili.com/login",
}


def to_netscape(cookies: list[dict]) -> str:
    """Serialize Playwright cookies into Netscape cookies.txt format."""
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by neko_downloader scripts/get-cookies.py",
        "",
    ]
    for c in cookies:
        domain = c["domain"]
        expires = int(c.get("expires") or 0)
        lines.append(
            "\t".join(
                [
                    domain,
                    "TRUE" if domain.startswith(".") else "FALSE",
                    c.get("path", "/"),
                    "TRUE" if c.get("secure") else "FALSE",
                    str(max(expires, 0)),  # -1 (session cookie) -> 0
                    c["name"],
                    c["value"],
                ]
            )
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="登入網站並匯出 cookies.txt")
    parser.add_argument("site", help=f"平台名稱（{'/'.join(SITES)}）或任意登入頁網址")
    parser.add_argument("-o", "--output", default="cookies.txt", help="輸出路徑（預設 cookies.txt）")
    args = parser.parse_args()

    url = SITES.get(args.site.lower(), args.site)
    if not url.startswith(("http://", "https://")):
        parser.error(f"未知的平台名稱：{args.site}（可用：{', '.join(SITES)}，或直接給網址）")

    from playwright.sync_api import sync_playwright

    with sync_playwright() as p:
        try:
            browser = p.chromium.launch(headless=False)
        except Exception as exc:
            print(f"無法開啟瀏覽器視窗：{exc}", file=sys.stderr)
            print(
                "提示：此工具需要圖形介面。請在你的桌面電腦執行本腳本，"
                "或先執行 backend/.venv/bin/playwright install chromium。",
                file=sys.stderr,
            )
            return 1
        context = browser.new_context()
        page = context.new_page()
        page.goto(url)
        print(f"已開啟 {url}")
        print("請在瀏覽器視窗中完成登入（含兩步驟驗證）。")
        input("登入完成後，回到這裡按 Enter 匯出 cookies… ")
        cookies = context.cookies()
        browser.close()

    if not cookies:
        print("沒有取得任何 cookies，是否尚未登入？", file=sys.stderr)
        return 1

    out = Path(args.output)
    out.write_text(to_netscape(cookies), encoding="utf-8")
    try:
        out.chmod(0o600)  # cookies 等同帳號憑證，限制檔案權限
    except OSError:
        pass
    print(f"已匯出 {len(cookies)} 個 cookies 到 {out}")
    print(f"接著在 .env 設定：COOKIES_FILE={out.resolve()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
